"""initial_rewrite_baseline

Revision ID: cd672d996585
Revises: 
Create Date: 2026-09-05 23:33:05.955626

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = 'cd672d996585'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_alerts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_alerts_vendor_slug'), ['vendor_slug'], unique=False)

    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_schema_hash', sa.String(length=64), nullable=True),
    sa.Column('request_body_hash', sa.String(length=64), nullable=True),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_details', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_vendor_slug'), ['vendor_slug'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drift_alert_id', sa.Integer(), nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('changelog_snippets', sa.JSON(), nullable=True),
    sa.Column('doc_references', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drift_alert_id'], ['drift_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_detection_runs_vendor_slug'))

    op.drop_table('detection_runs')
    with op.batch_alter_table('spec_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_snapshots_vendor_slug'))

    op.drop_table('spec_snapshots')
    with op.batch_alter_table('changelog_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_index(batch_op.f('ix_changelog_entries_run_id'))
        batch_op.drop_index(batch_op.f('ix_changelog_entries_tenant_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('method')
        batch_op.drop_column('path')
        batch_op.drop_column('kind')
        batch_op.drop_column('run_id')
        batch_op.drop_column('detail')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drift_alert_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'drift_alerts', ['drift_alert_id'], ['id'])

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_provider', sa.String(length=32), nullable=False))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('old_spec_url')
        batch_op.drop_column('spec_url')
        batch_op.drop_column('poll_interval_seconds')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_interval_seconds', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('spec_url', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('old_spec_url', sa.TEXT(), nullable=True))

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('git_provider')

    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('drift_alert_id')

    with op.batch_alter_table('changelog_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('run_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('path', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_slug'], ['slug'])
        batch_op.create_foreign_key(None, 'detection_runs', ['run_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_changelog_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changelog_entries_run_id'), ['run_id'], unique=False)
        batch_op.drop_column('fetched_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('content')
        batch_op.drop_column('title')
        batch_op.drop_column('source_url')

    op.create_table('spec_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('digest', sa.VARCHAR(length=16), nullable=False),
    sa.Column('etag', sa.VARCHAR(length=256), nullable=True),
    sa.Column('fetched_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_slug'], ['vendors.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spec_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_snapshots_vendor_slug'), ['vendor_slug'], unique=False)

    op.create_table('detection_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('old_digest', sa.VARCHAR(length=16), nullable=True),
    sa.Column('new_digest', sa.VARCHAR(length=16), nullable=True),
    sa.Column('breaking_count', sa.INTEGER(), nullable=False),
    sa.Column('additive_count', sa.INTEGER(), nullable=False),
    sa.Column('changes', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_slug'], ['vendors.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_runs_vendor_slug'), ['vendor_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_runs_tenant_id'), ['tenant_id'], unique=False)

    op.drop_table('investigations')
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_vendor_slug'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_tenant_id'))

    op.drop_table('telemetry_events')
    with op.batch_alter_table('drift_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_alerts_vendor_slug'))
        batch_op.drop_index(batch_op.f('ix_drift_alerts_tenant_id'))

    op.drop_table('drift_alerts')
    # ### end Alembic commands ###
