"""baseline

Revision ID: cd7a0398601e
Revises: 
Create Date: 2026-09-03 19:20:57.118980

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cd7a0398601e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_installations_install_id'), 'app_installations', ['install_id'], unique=True)
    op.create_index(op.f('ix_app_installations_owner'), 'app_installations', ['owner'], unique=False)
    op.create_index(op.f('ix_app_installations_tenant_id'), 'app_installations', ['tenant_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_tenant_id'), 'repositories', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('spec_url', sa.Text(), nullable=False),
    sa.Column('old_spec_url', sa.Text(), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('detection_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('old_digest', sa.String(length=16), nullable=True),
    sa.Column('new_digest', sa.String(length=16), nullable=False),
    sa.Column('breaking_count', sa.Integer(), nullable=False),
    sa.Column('additive_count', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_slug'], ['vendors.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_runs_tenant_id'), 'detection_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_detection_runs_vendor_slug'), 'detection_runs', ['vendor_slug'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_repository_id'), 'pipeline_runs', ['repository_id'], unique=False)
    op.create_table('spec_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=16), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_slug'], ['vendors.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_snapshots_vendor_slug'), 'spec_snapshots', ['vendor_slug'], unique=False)
    op.create_table('changelog_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_slug', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['detection_runs.id'], ),
    sa.ForeignKeyConstraint(['vendor_slug'], ['vendors.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changelog_entries_run_id'), 'changelog_entries', ['run_id'], unique=False)
    op.create_index(op.f('ix_changelog_entries_tenant_id'), 'changelog_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_changelog_entries_vendor_slug'), 'changelog_entries', ['vendor_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changelog_entries_vendor_slug'), table_name='changelog_entries')
    op.drop_index(op.f('ix_changelog_entries_tenant_id'), table_name='changelog_entries')
    op.drop_index(op.f('ix_changelog_entries_run_id'), table_name='changelog_entries')
    op.drop_table('changelog_entries')
    op.drop_index(op.f('ix_spec_snapshots_vendor_slug'), table_name='spec_snapshots')
    op.drop_table('spec_snapshots')
    op.drop_index(op.f('ix_pipeline_runs_repository_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_detection_runs_vendor_slug'), table_name='detection_runs')
    op.drop_index(op.f('ix_detection_runs_tenant_id'), table_name='detection_runs')
    op.drop_table('detection_runs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repositories_tenant_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_app_installations_tenant_id'), table_name='app_installations')
    op.drop_index(op.f('ix_app_installations_owner'), table_name='app_installations')
    op.drop_index(op.f('ix_app_installations_install_id'), table_name='app_installations')
    op.drop_table('app_installations')
    # ### end Alembic commands ###
