from __future__ import annotations

from dataclasses import dataclass

from app.fix.agent import fix_impact_on_content
from app.github.ci import CiTimeoutError, failure_message, wait_for_checks


@dataclass(frozen=True)
class PRLoopResult:
    pr_number: int
    pr_url: str
    passed: bool
    attempts: int
    failure: str | None = None


def push_files(
    client, owner: str, repo: str, branch: str, files: dict[str, str], message: str
) -> None:
    for path, content in files.items():
        existing = client.get_file(owner, repo, path, ref=branch)
        if existing:
            client.update_file(owner, repo, path, message, content, existing["sha"], branch)
        else:
            client.create_file(owner, repo, path, message, content, branch)


def build_pr_body(summary: str, details: list[str]) -> str:
    lines = [summary, "", "## Breaking changes addressed", ""]
    lines.extend(f"- {detail}" for detail in details)
    return "\n".join(lines)


def run_pr_loop(
    client,
    owner: str,
    repo: str,
    *,
    base: str,
    branch: str,
    files: dict[str, str],
    impacts,
    suggestion_model,
    max_attempts: int = 3,
    check_timeout: float = 300.0,
    check_interval: float = 10.0,
    title: str = "argus: fix breaking API changes",
    body: str = "Automated fix generated by Argus.",
) -> PRLoopResult:
    base_sha = client.branch_head_sha(owner, repo, base)
    if client.get_ref(owner, repo, branch) is None:
        client.create_branch(owner, repo, branch, base_sha)
    push_files(client, owner, repo, branch, files, f"{title} [initial fix]")
    pr = client.open_pull_request(owner, repo, title, branch, base, body)

    for attempt in range(1, max_attempts + 1):
        try:
            checks = wait_for_checks(client, owner, repo, pr.head_sha, check_timeout, check_interval)
        except CiTimeoutError as exc:
            client.pr_comment(
                owner, repo, pr.number, f"argus: giving up after {attempt} attempt(s).\n\n{exc}"
            )
            return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=attempt, failure=str(exc))
        failed = [check for check in checks if check.conclusion == "failure"]
        if not failed:
            return PRLoopResult(pr.number, pr.html_url, passed=True, attempts=attempt)

        msg = failure_message(client, owner, repo, pr.head_sha, checks)
        if attempt == max_attempts:
            client.pr_comment(
                owner, repo, pr.number, f"argus: giving up after {attempt} attempt(s).\n\n{msg}"
            )
            return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=attempt, failure=msg)

        client.pr_comment(
            owner, repo, pr.number, f"argus: CI failed on attempt {attempt}.\n\n{msg}\n\nRetrying fixes..."
        )
        for impact in impacts:
            path = impact.usage.file
            content = files.get(path)
            if content is None:
                continue
            fixed, err = fix_impact_on_content(
                impact, path, content, suggestion_model, previous_error=msg
            )
            if fixed is not None:
                files[path] = fixed
            else:
                client.pr_comment(
                    owner, repo, pr.number, f"argus: fix agent failed on {path} (attempt {attempt}): {err}"
                )
        push_files(client, owner, repo, branch, files, f"{title} [attempt {attempt + 1}]")
        pr = client.get_pull(owner, repo, pr.number)

    return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=max_attempts, failure="unreachable")
