from __future__ import annotations

import time
from dataclasses import dataclass

from app.fix.agent import fix_impact_on_content
from app.github.ci import CiTimeoutError, failure_message, wait_for_checks
from app.github.client import GitHubApiError


@dataclass(frozen=True)
class PRLoopResult:
    pr_number: int
    pr_url: str
    passed: bool
    attempts: int
    failure: str | None = None


def _branch_head(
    client, owner: str, repo: str, branch: str, prev_sha: str, max_wait: float = 30.0
) -> str:
    deadline = time.monotonic() + max_wait
    while time.monotonic() < deadline:
        try:
            sha = client.branch_head_sha(owner, repo, branch)
        except GitHubApiError:
            sha = prev_sha
        if sha != prev_sha:
            return sha
        time.sleep(2)
    return prev_sha


def push_files(
    client, owner: str, repo: str, branch: str, files: dict[str, str], message: str
) -> None:
    for path, content in files.items():
        existing = client.get_file(owner, repo, path, ref=branch)
        if existing:
            client.update_file(owner, repo, path, message, content, existing["sha"], branch)
        else:
            client.create_file(owner, repo, path, message, content, branch)


def build_pr_body(summary: str, details: list[str]) -> str:
    lines = [summary, "", "## Breaking changes addressed", ""]
    lines.extend(f"- {detail}" for detail in details)
    return "\n".join(lines)


def run_pr_loop(
    client,
    owner: str,
    repo: str,
    *,
    base: str,
    branch: str,
    files: dict[str, str],
    impacts,
    suggestion_model,
    max_attempts: int = 3,
    check_timeout: float = 300.0,
    check_interval: float = 10.0,
    base_url: str | None = None,
    title: str = "argus: fix breaking API changes",
    body: str = "Automated fix generated by Argus.",
    vendor_guidance: str | None = None,
) -> PRLoopResult:
    base_sha = client.branch_head_sha(owner, repo, base)
    if client.get_ref(owner, repo, branch) is None:
        client.create_branch(owner, repo, branch, base_sha)

    failed_fixes: list[tuple[object, str]] = []
    for impact in impacts:
        content = files.get(impact.usage.file)
        if content is None:
            continue
        fixed, err = fix_impact_on_content(
            impact,
            impact.usage.file,
            content,
            suggestion_model,
            previous_error=None,
            base_url=base_url,
            vendor_guidance=vendor_guidance,
        )
        if fixed is not None:
            files[impact.usage.file] = fixed
        else:
            failed_fixes.append((impact, err))

    if failed_fixes and len(failed_fixes) == len(impacts):
        detail = "; ".join(
            f"{i.usage.file}:{i.usage.line} -> {err}" for i, err in failed_fixes
        )
        print(f"argus: fix agent produced no patches: {detail}")
        return PRLoopResult(
            pr_number=0,
            pr_url="",
            passed=False,
            attempts=0,
            failure=f"fix agent failed to produce any patch: {detail}",
        )

    push_files(client, owner, repo, branch, files, f"{title} [initial fix]")
    pr = client.open_pull_request(owner, repo, title, branch, base, body)
    if failed_fixes:
        detail = "\n".join(f"- {i.usage.file}:{i.usage.line}: {err}" for i, err in failed_fixes)
        client.pr_comment(
            owner,
            repo,
            pr.number,
            f"argus: initial fix failed on {len(failed_fixes)} call site(s):\n{detail}",
        )
    head_sha = pr.head_sha

    for attempt in range(1, max_attempts + 1):
        try:
            checks = wait_for_checks(client, owner, repo, head_sha, check_timeout, check_interval)
        except CiTimeoutError as exc:
            client.pr_comment(
                owner, repo, pr.number, f"argus: giving up after {attempt} attempt(s).\n\n{exc}"
            )
            return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=attempt, failure=str(exc))
        failed = [check for check in checks if check.conclusion == "failure"]
        if not failed:
            return PRLoopResult(pr.number, pr.html_url, passed=True, attempts=attempt)

        msg = failure_message(client, owner, repo, head_sha, checks)
        if attempt == max_attempts:
            client.pr_comment(
                owner, repo, pr.number, f"argus: giving up after {attempt} attempt(s).\n\n{msg}"
            )
            return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=attempt, failure=msg)

        client.pr_comment(
            owner, repo, pr.number, f"argus: CI failed on attempt {attempt}.\n\n{msg}\n\nRetrying fixes..."
        )
        before = dict(files)
        for impact in impacts:
            path = impact.usage.file
            content = files.get(path)
            if content is None:
                continue
            fixed, err = fix_impact_on_content(
                impact, path, content, suggestion_model, previous_error=msg, base_url=base_url,
                vendor_guidance=vendor_guidance,
            )
            if fixed is not None:
                files[path] = fixed
            else:
                client.pr_comment(
                    owner, repo, pr.number, f"argus: fix agent failed on {path} (attempt {attempt}): {err}"
                )
        if files == before:
            msg = "fix agent produced no new patches during retry"
            client.pr_comment(owner, repo, pr.number, f"argus: giving up after {attempt} attempt(s).\n\n{msg}")
            return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=attempt, failure=msg)
        push_files(client, owner, repo, branch, files, f"{title} [attempt {attempt + 1}]")
        head_sha = _branch_head(client, owner, repo, branch, head_sha)

    return PRLoopResult(pr.number, pr.html_url, passed=False, attempts=max_attempts, failure="unreachable")
